[browser]
gatherUsageStats = false

[server]
fileWatcherType = "none"

[runner]
magicEnabled = false

[theme]
base = "light"
primaryColor = "#EE0011"
backgroundColor = "#F6F0E2"
secondaryBackgroundColor = "#EDE7D9"
textColor = "#000000"
font = "sans serif"
